### ISSUE TITLE
file.isNull is not a function & Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by ryuever** [sahat/newedenfaces-react#10]
For recently, I am deploying project on the local machine. However it has two issues when run command **npm install**.

    /react/newedenfaces-react/node_modules/gulp-streamify/src/index.js:30
        if(file.isNull() || file.isBuffer()) {
                ^
    
    TypeError: file.isNull is not a function
        at Transform.inputStream._transform (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/gulp-streamify/src/index.js:30:13)
        at Transform._read (_stream_transform.js:167:10)
        at Transform._write (_stream_transform.js:155:12)
        at doWrite (_stream_writable.js:292:12)
        at writeOrBuffer (_stream_writable.js:278:5)
        at Transform.Writable.write (_stream_writable.js:207:11)
        at Duplexer._write (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/src/index.js:112:25)
        at doWrite (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/node_modules/readable-stream/lib/_stream_writable.js:335:12)
        at writeOrBuffer (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/node_modules/readable-stream/lib/_stream_writable.js:321:5)
        at Duplexer.Writable.write (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/node_modules/readable-stream/lib/_stream_writable.js:248:11)

According to [strange gulp-uglify minifier 'file.isNull()' error on gulp build](http://stackoverflow.com/questions/33201066/strange-gulp-uglify-minifier-file-isnull-error-on-gulp-build), I removed the extra parenthesis of **file.isNull() || file.isBuffer()** in file **gulp-streamify/src/index.js**  for temporary fix. 

Then rerun with command **bower install && gulp build**, it exits with the following error message.

    /react/newedenfaces-react/node_modules/gulp-streamify/src/index.js:53
        originalStream.pipe(bufstream);
                      ^
    
    TypeError: Cannot read property 'pipe' of undefined
        at Transform.inputStream._transform (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/gulp-streamify/src/index.js:53:19)
        at Transform._read (_stream_transform.js:167:10)
        at Transform._write (_stream_transform.js:155:12)
        at doWrite (_stream_writable.js:292:12)
        at writeOrBuffer (_stream_writable.js:278:5)
        at Transform.Writable.write (_stream_writable.js:207:11)
        at Duplexer._write (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/src/index.js:112:25)
        at doWrite (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/node_modules/readable-stream/lib/_stream_writable.js:335:12)
        at writeOrBuffer (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/node_modules/readable-stream/lib/_stream_writable.js:321:5)
        at Duplexer.Writable.write (/Users/ryu/Documents/git/react/newedenfaces-react/node_modules/plexer/node_modules/readable-stream/lib/_stream_writable.js:248:11)

**Comment by o0ochina** [comment]
if(file || file.isBuffer()) {

**Comment by sahat** [comment]
@ryuever Try using vynil-buffer (https://www.npmjs.com/package/vinyl-buffer) instead of gulp-streamify.

**Comment by sahat** [comment]
This should be fixed in f4cefafbc906e313fd616886559f0c3a47f64747. I updated the tutorial as well.
